INSERT INTO brewery 
(`name`, `brewmaster`, `description`, `latitude`, `longitude`) 
VALUES
('Cervejaria Águia Dourada', 'João Mendes', 'Fundada no coração de Pernambuco em 2017, a Cervejaria Águia Dourada rapidamente se destacou no cenário das cervejas artesanais. Inspirada pela rica cultura local e pela paixão dos pernambucanos por sabores autênticos, a Águia Dourada foi pioneira em incorporar ingredientes regionais em suas receitas, criando cervejas únicas que refletem a alma do estado. Durante a pandemia, a cervejaria soube se reinventar, ampliando sua presença digital e alcançando um público mais amplo através de vendas online, que hoje representam uma parcela significativa do seu negócio. Sempre inovadora, lançou a linha de cervejas "Sertão Vivo", que inclui uma IPA com toques de frutas tropicais e uma Stout com nuances de café local, além de uma linha de destilados artesanais, como a cachaça "Sol do Agreste", que rapidamente se tornou um sucesso de vendas. A Cervejaria Águia Dourada continua a voar alto, comprometida com a qualidade e a tradição, enquanto explora novos horizontes no mundo das bebidas artesanais.',-35.0000,-8.0000),
('Brewmasters do Sol', 'Ana Silva', 'Fundada sob o calor tropical de Pernambuco em 2018, a Brewmasters do Sol rapidamente se tornou um símbolo da revolução das cervejas artesanais na região. Inspirada pela paixão de seu fundador, João Cardoso, a cervejaria abraçou a missão de inovar no mercado, trazendo sabores únicos que refletem a alma pernambucana. Durante os desafios impostos pela pandemia, a Brewmasters do Sol expandiu sua presença, equilibrando vendas entre o ambiente digital e os tradicionais pontos de encontro, onde suas cervejas são apreciadas por conhecedores e novatos. Com destaque para a sua premiada IPA Solar e a refrescante Lager Litorânea, a Brewmasters do Sol também explorou novos territórios com o lançamento do cachaça artesanal Aurora Tropical, que captura a essência vibrante do estado em cada gole. A marca continua a crescer, mantendo-se fiel às suas raízes e à comunidade que a viu nascer.',-35.0000, -8.0000),
('Espuma dos Deuses', 'Carlos Eduardo', 'Fundada na rica tradição cervejeira de Pernambuco, a Espuma dos Deuses rapidamente se tornou um símbolo da inovação e da paixão pelas cervejas artesanais. Desde o seu nascimento em 2020, a cervejaria tem se dedicado a criar sabores únicos que capturam a essência do estado, misturando técnicas tradicionais com um toque moderno. O fundador João Andrade, um mestre cervejeiro com visão de futuro, guiou a empresa através dos desafios do mercado, incluindo os tempos difíceis da pandemia, mantendo o compromisso com a qualidade e a satisfação do cliente. Com uma linha de produtos que inclui desde a refrescante Pilsen Tropical até o robusto Stout do Sertão, a Espuma dos Deuses também se aventurou no mundo dos destilados, lançando a cachaça Artesanal de Engenho, que rapidamente conquistou paladares. A cervejaria celebra a cultura local e se orgulha de ser um ponto de encontro para os amantes de cerveja, oferecendo tours em suas instalações e vendas tanto em seu taproom quanto online, onde a experiência virtual é tão envolvente quanto a presencial.',-35.0000, -8.0000),
('Lúpulo Feliz', 'Mariana Costa', 'Fundada no coração de Pernambuco em 2017, a Lúpulo Feliz rapidamente se tornou um símbolo da revolução das cervejas artesanais na região. Inspirada pela rica cultura local e pela paixão dos seus fundadores, João Silva e Ana Costa, a cervejaria abraçou a missão de criar cervejas que refletem o espírito pernambucano. Com uma abordagem inovadora e adaptativa, a Lúpulo Feliz superou os desafios do mercado, especialmente durante os tempos incertos da pandemia, mantendo-se firme no compromisso com a qualidade e a autenticidade. A cervejaria oferece uma gama de produtos que inclui desde a refrescante IPA Tropical até o robusto Stout de Mandioca, conquistando o paladar dos consumidores. Além disso, a Lúpulo Feliz expandiu sua presença para o comércio eletrônico, onde alcançou um impressionante aumento nas vendas. Mantendo-se à frente das tendências, lançou a linha de cervejas "Barrel Aged", envelhecidas em barris de madeira, e o destilado "Cana do Chefe", que rapidamente se tornou um favorito entre os apreciadores. Com um olhar sempre voltado para o futuro, a Lúpulo Feliz continua a inovar e a celebrar a arte da cervejaria artesanal.',-35.0000, -8.0000),
('Cervejaria Rio Cristalino', 'Patrícia Faria', 'Fundada na pitoresca região de Pernambuco em 2020, a Cervejaria Rio Cristalino rapidamente se tornou um marco na revolução das cervejas artesanais no Brasil. Inspirada pela natureza exuberante e pela clareza das águas que dão nome à cervejaria, a Rio Cristalino destaca-se pela sua dedicação em criar cervejas que refletem a alma pernambucana. Durante a pandemia, a cervejaria soube se adaptar às novas dinâmicas do mercado, expandindo sua presença para vendas online, onde hoje realiza uma significativa parcela de suas transações. Com um portfólio que inclui desde a refrescante Pilsen Cristal até o inovador gin Tropicália, leve e aromático, a Rio Cristalino não só conquistou paladares, mas também iniciou a produção de vodkas artesanais, mantendo-se na vanguarda do setor e honrando a tradição e inovação da cultura cervejeira artesanal.',-35.0000, -8.0000),
('Mestres da Cerveja', 'Eduardo Pereira', 'Fundada no coração de Pernambuco em 2015, a Mestres da Cerveja emergiu como uma pioneira no cenário das cervejas artesanais, crescendo em sintonia com o florescimento dessa cultura no Brasil. Inspirada pela paixão e pelo espírito inovador de seu fundador, João Andrade Silva, a cervejaria abraçou as mudanças do mercado com agilidade, especialmente durante os desafios impostos pela pandemia. Com uma presença robusta tanto em estabelecimentos locais quanto na esfera digital, a Mestres da Cerveja alcançou um marco impressionante ao realizar metade de suas vendas online. Mantendo-se à frente da concorrência, a cervejaria lançou a aclamada Pilsen Tropical, uma cerveja de malte puro com notas cítricas, e o gin Oceânico, uma bebida refrescante e acessível que rapidamente conquistou o paladar dos consumidores, impulsionando a marca a expandir seu portfólio com a introdução de vodkas artesanais.',-35.0000, -8.0000),
('Barley Brothers', 'Fernanda Gomes','Fundada na vibrante cena de cervejas artesanais de Pernambuco em 2018, a Barley Brothers rapidamente se destacou com sua abordagem inovadora e seu compromisso com a qualidade. Inspirada pela rica tradição cervejeira e pela diversidade cultural da região, a marca foi pioneira em introduzir estilos únicos que capturam a essência de Pernambuco. Durante a pandemia, a Barley Brothers adaptou-se com agilidade, ampliando sua presença online e alcançando um novo público através de vendas digitais, que representaram uma parcela significativa do seu faturamento. Com um portfólio que inclui desde a refrescante Pilsen Tropical até o robusto Stout do Sertão, além de uma linha de destilados que celebra os sabores locais, a Barley Brothers continua a inovar, mantendo-se fiel às suas raízes e contribuindo para a cultura cervejeira artesanal de Pernambuco.',-35.0000, -8.0000),
('Cervejaria Lago Azul', 'Roberto Nascimento','A Cervejaria Lago Azul, estabelecida em 2020 em Pernambuco, emergiu como um ícone da inovação no cenário das cervejas artesanais. Inspirada pela rica tradição cervejeira da região e pelo espírito empreendedor de seu fundador, João Cardoso, a cervejaria rapidamente se tornou sinônimo de qualidade e criatividade. Durante os desafios impostos pela pandemia, a Lago Azul adaptou-se com agilidade, fortalecendo sua presença no mercado digital e alcançando um impressionante 50% de suas vendas online. Com um portfólio diversificado que inclui a refrescante Pilsen Tropical e a inovadora cachaça artesanal Azul Marinho, a cervejaria não só conquistou paladares locais, mas também começou a explorar o mercado de destilados, mantendo-se na vanguarda do setor. A Lago Azul continua a honrar a cultura artesanal, enquanto navega com sucesso pelas ondas de um mercado em constante evolução.',-35.0000, -8.0000),
('Trigo e Companhia', 'Luciana Alves','Trigo e Companhia, estabelecida em 2016, floresceu em harmonia com o crescente apreço pelas cervejas artesanais em Pernambuco. Inspirada pela paixão e dedicação de seu fundador, João Barley, a cervejaria se tornou um símbolo da inovação no setor, promovendo a cultura cervejeira local. Durante os desafios impostos pela pandemia, Trigo e Companhia se adaptou com agilidade, expandindo sua presença para vendas online, que rapidamente representaram uma parcela significativa do seu faturamento. Mantendo-se à frente da concorrência, a cervejaria lançou a aclamada Pernambuco Weiss e a refrescante IPA Tropical, além de uma linha de destilados autênticos, como a cachaça artesanal Canavial, que conquistou o paladar dos consumidores e solidificou a Trigo e Companhia como uma marca versátil e de prestígio no mercado de bebidas artesanais.',-35.0000, -8.0000);


INSERT INTO beer 
(name, minimum_temperature, maximum_temperature, ibu, alcohol_content, description, type, volume, color, glass, body, aroma, malt, brewery_id) 
VALUES
('Águia Dourada IPA', 5, 8, 60, 6, 'Água Dourada IPA é uma cerveja artesanal que se destaca por seu sabor único e equilibrado. Com um aroma envolvente que remete a notas cítricas e um toque de malte, esta IPA oferece uma experiência sensorial rica. O amargor é bem balanceado, complementando o corpo médio e proporcionando um final de boca memorável. Água Dourada IPA é uma homenagem à riqueza natural e à vibrante cultura brasileira, refletindo a paixão e a arte da cervejaria em cada gole.', 'IPA', 500, 'Dourada', 'Pint', 70, 80, 60, 1),
('Águia Dourada Stout', 6, 10, 40, 8, 'Água Dourada Stout é uma cerveja robusta com nuances de café local e chocolate. Com corpo cremoso e bem estruturado, esta Stout proporciona uma experiência rica e intensa. As notas de malte torrado complementam seu sabor profundo, criando um equilíbrio perfeito entre doçura e amargor. Uma verdadeira homenagem às tradições cervejeiras.', 'Stout', 500, 'Preta', 'Pint', 80, 70, 90, 1),
('IPA Solar', 4, 7, 50, 6, 'IPA Solar é uma cerveja premiada que encanta os amantes do lúpulo. Com um aroma cítrico intenso e um sabor marcante, esta IPA oferece uma explosão de frescor a cada gole. O amargor equilibrado é complementado por um corpo leve e refrescante, tornando-a perfeita para qualquer ocasião.', 'IPA', 500, 'Dourada', 'Pint', 60, 75, 65, 2),
('Lager Litorânea', 3, 6, 20, 4, 'Lager Litorânea é uma cerveja refrescante, ideal para os dias ensolarados. Com notas leves de malte e um toque sutil de lúpulo, esta Lager é perfeita para quem busca uma bebida leve e saborosa. Seu corpo leve e aroma suave fazem dela a escolha ideal para momentos de descontração.', 'Lager', 500, 'Amarela', 'Caneca', 40, 50, 30, 2),
('Paradise Pilsner', 4, 7, 15, 5, 'Paradise Pilsner é uma cerveja refrescante que combina a leveza do estilo Pilsen com notas cítricas. Seu sabor suave e corpo leve são complementados por um aroma fresco, tornando-a perfeita para os dias quentes. Uma verdadeira celebração dos trópicos em cada gole.', 'Pilsen', 500, 'Dourada', 'Copo Pilsen', 35, 60, 40, 3),
('Cactus Shadow Stout', 5, 9, 45, 7, 'Cactus Shadow Stout é uma cerveja robusta e intensa, com sabores profundos de malte torrado e notas de café. Seu corpo encorpado e cremoso proporciona uma experiência rica e satisfatória. Uma homenagem à cultura sertaneja, refletida em cada detalhe desta cerveja.', 'Stout', 500, 'Preta', 'Pint', 85, 75, 85, 3),
('Citrus Surf IPA', 5, 8, 50, 6, 'Citrus Surf IPA é uma cerveja refrescante com uma explosão de sabores tropicais. Com notas cítricas e frutadas, esta IPA oferece um amargor bem balanceado e um corpo médio, tornando-a ideal para os dias ensolarados. Uma verdadeira celebração dos sabores tropicais.', 'IPA', 500, 'Dourada', 'Pint', 70, 80, 65, 4),
('Stout de Mandioca', 6, 9, 40, 7, 'Stout de Mandioca é uma cerveja robusta com um toque brasileiro. Feita com mandioca, esta Stout oferece um sabor único e marcante. As notas de malte torrado e chocolate são complementadas pelo corpo cremoso, proporcionando uma experiência rica e autêntica.', 'Stout', 500, 'Preta', 'Pint', 80, 70, 90, 4),
('Pilsen Cristal', 4, 7, 15, 5, 'Pilsen Cristal é uma cerveja refrescante e leve, perfeita para qualquer ocasião. Com um corpo leve e um sabor suave, esta Pilsen oferece uma experiência de bebida agradável e revigorante. Ideal para momentos de descontração.', 'Pilsen', 500, 'Dourada', 'Copo Pilsen', 30, 55, 35, 5),
('Gin Tropicália', 6, 8, 0, 40, 'Gin Tropicália é um gin leve e aromático, perfeito para cocktails. Com notas de frutas tropicais e ervas, este gin oferece uma experiência refrescante e sofisticada. Ideal para quem busca um toque de exotismo em suas bebidas.', 'Gin', 750, 'Transparente', 'Taça', 0, 85, 0, 5),
('Tropical Breeze Lager', 4, 7, 15, 5, 'Tropical Breeze Lager é uma cerveja refrescante com notas cítricas. Seu corpo leve e sabor suave são complementados por um aroma fresco, tornando-a ideal para os dias quentes. Uma celebração dos sabores tropicais.', 'Pilsen', 500, 'Dourada', 'Copo Pilsen', 35, 60, 40, 6),
('Gin Oceânico', 6, 8, 0, 40, 'Gin Oceânico é um gin refrescante com notas de ervas e especiarias. Ideal para cocktails, este gin oferece uma experiência sofisticada e revigorante. Perfeito para quem busca um toque de frescor em suas bebidas.', 'Gin', 750, 'Transparente', 'Taça', 0, 80, 0, 6),
('Island Hopper Pils', 4, 7, 15, 5, 'Island Hopper Pils é uma cerveja refrescante com um toque de cítricos. Seu corpo leve e sabor suave são complementados por um aroma fresco, tornando-a perfeita para os dias ensolarados. Uma celebração dos trópicos em cada gole.', 'Pilsen', 500, 'Dourada', 'Copo Pilsen', 35, 60, 40, 7),
('Stout do Sertao', 6, 9, 45, 7, 'Stout do Sertão é uma cerveja robusta e intensa, com sabores profundos de malte torrado e notas de café. Seu corpo encorpado e cremoso proporciona uma experiência rica e satisfatória. Uma homenagem à cultura sertaneja, refletida em cada detalhe desta cerveja.', 'Stout', 500, 'Preta', 'Pint', 85, 75, 85, 7),
('Pilsen Tropical', 4, 7, 15, 5, 'Pilsen Tropical é uma cerveja refrescante com um toque de cítricos. Seu corpo leve e sabor suave são complementados por um aroma fresco, tornando-a ideal para os dias ensolarados. Uma celebração dos trópicos em cada gole.', 'Pilsen', 500, 'Dourada', 'Copo Pilsen', 35, 60, 40, 8),
('Cachaça Azul Marinho', 8, 12, 0, 40, 'Cachaça Azul Marinho é uma cachaça artesanal, perfeita para ser degustada pura ou em cocktails. Com um sabor marcante e suave, esta cachaça é uma homenagem às tradições brasileiras, refletindo a arte e a paixão em sua produção.', 'Cachaça', 700, 'Transparente', 'Copo de Cachaça', 0, 90, 0, 8),
('Pernambuco Weiss', 5, 8, 20, 5, 'Pernambuco Weiss é uma cerveja de trigo refrescante com notas cítricas. Seu corpo leve e sabor frutado proporcionam uma experiência agradável e revigorante. Ideal para os dias quentes.', 'Weiss', 500, 'Dourada', 'Copo Weiss', 50, 65, 55, 9),
('IPA Tropical', 4, 7, 50, 6, 'IPA Tropical é uma cerveja refrescante com uma explosão de sabores tropicais. Com notas cítricas e frutadas, esta IPA oferece um amargor bem balanceado e um corpo médio, tornando-a ideal para os dias ensolarados. Uma verdadeira celebração dos sabores tropicais.', 'IPA', 500, 'Dourada', 'Pint', 70, 80, 65, 9);

INSERT INTO harmonization (food, beer_id) VALUES
('Buffalo Wings', 1),
('Spicy Tacos', 1),
('Grilled Salmon', 1),
('Cheddar Cheese', 1),
('Citrus Salad', 1),
('Chocolate Cake', 2),
('Beef Stew', 2),
('Smoked Gouda', 2),
('Espresso', 2),
('Roasted Nuts', 2),
('Grilled Shrimp', 3),
('Thai Curry', 3),
('Blue Cheese', 3),
('Mango Salsa', 3),
('Lemon Tart', 3),
('Fish and Chips', 4),
('Caesar Salad', 4),
('Mild Cheddar', 4),
('Lemon Chicken', 4),
('Pretzels', 4),
('Grilled Chicken', 5),
('Bratwurst', 5),
('Swiss Cheese', 5),
('Apple Strudel', 5),
('Crab Cakes', 5),
('Chocolate Brownies', 6),
('Beef Wellington', 6),
('Aged Cheddar', 6),
('Black Coffee', 6),
('Pecan Pie', 6),
('Fish Tacos', 7),
('Spicy Noodles', 7),
('Gorgonzola', 7),
('Pineapple Sorbet', 7),
('Crispy Tofu', 7),
('BBQ Ribs', 8),
('Porterhouse Steak', 8),
('Parmesan Cheese', 8),
('Hot Chocolate', 8),
('Toasted Marshmallows', 8),
('Sushi', 9),
('Grilled Vegetables', 9),
('Brie Cheese', 9),
('Fruit Tart', 9),
('Seafood Pasta', 9),
('Gin Martini', 10),
('Oysters', 10),
('Goat Cheese', 10),
('Citrus Sorbet', 10),
('Cucumber Salad', 10),
('Grilled Pork', 11),
('Spicy Salsa', 11),
('Camembert Cheese', 11),
('Pineapple Upside-down Cake', 11),
('Fried Plantains', 11),
('Gin and Tonic', 12),
('Ceviche', 12),
('Feta Cheese', 12),
('Lemon Pie', 12),
('Grilled Asparagus', 12),
('Crispy Fish', 13),
('Citrus Salad', 13),
('Havarti Cheese', 13),
('Mango Sorbet', 13),
('Garlic Bread', 13),
('Spicy Sausages', 14),
('Lamb Stew', 14),
('Aged Gouda', 14),
('Dark Chocolate', 14),
('Nutty Biscuits', 14),
('Shrimp Skewers', 15),
('Tropical Salad', 15),
('Fresh Mozzarella', 15),
('Coconut Cake', 15),
('Chicken Wings', 15),
('Feijoada', 16),
('BBQ Chicken', 16),
('Provolone Cheese', 16),
('Passion Fruit Mousse', 16),
('Roasted Peanuts', 16),
('Bratwurst', 17),
('German Potato Salad', 17),
('Muenster Cheese', 17),
('Apple Pie', 17),
('Soft Pretzels', 17),
('Grilled Steak', 18),
('Bean Soup', 18),
('Aged Parmesan', 18),
('Vanilla Ice Cream', 18),
('Grilled Peaches', 18);